# Generated by Django 4.0.8 on 2023-09-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cost', models.CharField(max_length=50)),
                ('property_type', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('locality', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('link', models.URLField(max_length=500)),
            ],
        ),
    ]
